// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDB_FCrovKd1E5-l8mv5ObTfdRI9bHrJYs',
    appId: '1:1009694556933:web:a04e910dc5327ddb42ad6c',
    messagingSenderId: '1009694556933',
    projectId: 'gallery-app-e97a6',
    authDomain: 'gallery-app-e97a6.firebaseapp.com',
    storageBucket: 'gallery-app-e97a6.appspot.com',
    measurementId: 'G-KCLLN4M09Z',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDXlpRRfgKZX5VBdm8TahKwcCGQf3-6WUE',
    appId: '1:1009694556933:android:9f560c355167bdc642ad6c',
    messagingSenderId: '1009694556933',
    projectId: 'gallery-app-e97a6',
    storageBucket: 'gallery-app-e97a6.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDr1G5AesECbw8iv-bg5g_6biuTwNwH1H4',
    appId: '1:1009694556933:ios:21e0c872bb16fd1c42ad6c',
    messagingSenderId: '1009694556933',
    projectId: 'gallery-app-e97a6',
    storageBucket: 'gallery-app-e97a6.appspot.com',
    iosBundleId: 'com.example.galleryApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDr1G5AesECbw8iv-bg5g_6biuTwNwH1H4',
    appId: '1:1009694556933:ios:d05071224f7ac21542ad6c',
    messagingSenderId: '1009694556933',
    projectId: 'gallery-app-e97a6',
    storageBucket: 'gallery-app-e97a6.appspot.com',
    iosBundleId: 'com.example.galleryApp.RunnerTests',
  );
}
